### ISSUE TITLE
fix: isValid is true in some cases when it should be false

### ISSUE THREAD

**Issue by parvatijay2901** [uw-ssec/post-disaster-comms#131]
Noticed that in some cases isValid is not set back to false:
![image](https://github.com/user-attachments/assets/07c6f580-8c6b-4b0e-82e8-fc9c9e260021)
![image](https://github.com/user-attachments/assets/1b292f8b-5b42-4ca2-9155-b7490a3f3aaf)

**Comment by lsetiawan** [comment]
Checking in on this issue, is this still showing up?

**Comment by parvatijay2901** [comment]
> Checking in on this issue, is this still showing up?

Yes, I can work on it maybe this week.

**Comment by parvatijay2901** [comment]
Solved in PR #130
