### ISSUE TITLE
feat: Add ability to edit personal and household information on the user profile

### ISSUE THREAD

**Issue by nikiburggraf** [uw-ssec/post-disaster-comms#137]
there are buttons to edit these fields, but they currently only pull up empty bottom drawers. Add the ability to edit this information and save it to the database

**Don't** allow them to update their emails. Name/phone number should be editable in the user info section however

In "edit household" mode -- allow them to edit address, pets, accessibility needs, and notes. Display the household members but don't allow edits

~~For household members, don't allow updates to `Person`s that have `User` profiles.~~ (this whole thing is out of scope for this task, pls disregard)

**Comment by lsetiawan** [comment]
Please use the https://pub.dev/packages/form_builder_validators for validating fields

**Comment by hinxcode** [comment]
make max_household_member_number a constant
