### ISSUE TITLE
feat: Individual checklist page

### ISSUE THREAD

**Issue by nikiburggraf** [uw-ssec/post-disaster-comms#141]
## Description

Everything needed to allow users to view details of and complete individual checklists

Including the following requirements: 

- including setting list as done when all items done
- set TTL/time to recomplete when list done or whatever

## UI

<img width="241" alt="Screenshot 2024-10-22 at 4 44 12 PM" src="https://github.com/user-attachments/assets/a673deb6-aa91-4307-9db3-c64e42af178b">

<img width="244" alt="Screenshot 2024-10-22 at 4 44 22 PM" src="https://github.com/user-attachments/assets/beb4d10c-bd58-4810-9dca-e948207c494e">

<img width="246" alt="Screenshot 2024-10-22 at 4 44 30 PM" src="https://github.com/user-attachments/assets/6783ff24-e1c0-4748-a2ce-effb12ecb088">

**Comment by lsetiawan** [comment]
> set TTL/time to recomplete when list done or whatever

@hinxcode and I discussed that this is better to be done in the backend as a daily cron job checks.
