### ISSUE TITLE
chore: Cloud deployment setup

### ISSUE THREAD

**Issue by nikiburggraf** [uw-ssec/post-disaster-comms#16]
## Overview

We need a cloud deployment setup using Infrastructure as code, utilizing [OpenTofu](https://opentofu.org/)

## Specification

- Cloud Provider: AWS ... @lsetiawan to provide access
- Machine type: EC2 (Possible R5 Large to start)
- OS: ubuntu
- Setup: [Cloud Init](https://cloudinit.readthedocs.io/en/latest/reference/examples.html)

## Action Items
- [ ] Create cloud config
- [ ] Test cloud config locally with QEMU. See [docs](https://cloudinit.readthedocs.io/en/latest/howto/run_cloud_init_locally.html#run-with-qemu)
- [ ] Add CI for cloud config test to GH Action
- [ ] Create OpenTofu configuration with custom VPC and EC2 instance and cloud config
- [ ] Test out the OpenTofu configuration manually
- [ ] Create docs on how to spin up and tear down machine
- [ ] Add cloud watch configuration to track spending
- [x] Add some mechanism for instance management.. @nikiburggraf to look into what this looks like

**Comment by nikiburggraf** [comment]
cw alarm on instance uptime -> eventbridge to terminate running instance OR trigger lambda to do the same

**Comment by nikiburggraf** [comment]
dev stack / prod stack?

**Comment by nikiburggraf** [comment]
terragrunt might be useful for multistack

**Comment by nikiburggraf** [comment]
def need some IAM roles too

**Comment by nikiburggraf** [comment]
add awscli & opentofu/terragrunt/whatever else to pixi.toml if/as needed

**Comment by nikiburggraf** [comment]
docker should install + run as part of cloud-init, pixi also and pixi should install most other things

don todo: provide pixi instructions JUST for running database stuff

**Comment by nikiburggraf** [comment]
IN THE WEEDS CLOUD QUESTIONS: 
* do we want multi-AZ, multi-region resiliency? how do we keep data synced between these separate instances if so?
* what happens if the instance we're using goes down? do we have backups for the data sent to s3 every day and bring it back from there?

**Comment by lsetiawan** [comment]
@nikiburggraf I've added #61 as another task related to this to ensure security for our cloud deployment of supabase.
