### ISSUE TITLE
Errors starting `pixi run fast-api-server-dev`

### ISSUE THREAD

**Issue by philion** [uw-ssec/post-disaster-comms#226]
While following the instructions from https://pdc-ssec.readthedocs.io/en/latest/, I got to the last step in Backend setup, and run into errors cpnnecting to the database.

The error from: `pixi run fast-api-server-dev`

> OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: server closed the connection unexpectedly
>         This probably means the server terminated abnormally
>         before or while processing the request.

I also check the container running the suprabase instance:

Error from container, via `docker logs -f k3d-pdc-cluster-serverlb`

> 2024/12/19 18:07:13 [error] 51#51: *37 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: 0.0.0.0:5432, upstream: "172.19.0.3:5432", bytes from/to client:0/0, bytes from/to upstream:0/0

I also tried running the `fast-api-server-run` to see if that made a difference (as per docs), but that's not actually implemented.
			
> pixi run fast-api-server-run
> fast-api-server-run: command not found

**Comment by lsetiawan** [comment]
Thanks for raising this issue @philion. Yes we actually don't have the fastapi server implemented. We'll update the docs so it's not so confusing. Really appreciate you trying it out 😄
