### ISSUE TITLE
Implement database design to Supabase PostgreSQL

### ISSUE THREAD

**Issue by nikiburggraf** [uw-ssec/post-disaster-comms#25]
https://dbdiagram.io/d/PDC-Database-66abcd508b4bb5230efde1c3

**Comment by anujsinha3** [comment]
- [ ] add task for port forwarding for supabase on docker container
- [ ] add SQLModel as ORM and pycopg2 as db driver
- [ ] setup connection with Postgres
- [ ] setup model directory structure
- [ ] implement db operations by using model-based repository
- [ ] setup user and user_profile model/tables

**Comment by anujsinha3** [comment]
Closing this issue.

Will keep on adding additional models as required as part of separate issues.
