### ISSUE TITLE
feat: Add authZ capabilities

### ISSUE THREAD

**Issue by nikiburggraf** [uw-ssec/post-disaster-comms#30]
figure out access control mechanisms (frontend only? cors to restrict access to supabase from non-app-initiated calls? database roles???)

### Potential Resources/Learnings

* https://wordpress.org/documentation/article/roles-and-capabilities/
* https://learn.wordpress.org/tutorial/developing-with-user-roles-and-capabilities/
* https://supabase.com/docs/guides/database/postgres/row-level-security

**Comment by lsetiawan** [comment]
Following up on this. We'll need to implement a custom claim and RBAC access: https://supabase.com/docs/guides/database/postgres/custom-claims-and-role-based-access-control-rbac?queryGroups=language&language=plpgsql

This way we can access the user_role info directly from the JWT token.

**Comment by nikiburggraf** [comment]
for a basic permission, we can have one for changing emergency state (more specifically, updating the `operational_event` table), which should only be available to LEAP.

**Comment by nikiburggraf** [comment]
Will need to create 2 enums in sqlalchemy. one for roles, one for capabilities.

**Comment by lsetiawan** [comment]
Please add the sql function into the db config as a new key value pair:

https://github.com/uw-ssec/post-disaster-comms/blob/0f0a4b422c3202c4c76942f6feaf057a3ca7c393/deployment/values.dev.yaml#L34-L40
