### ISSUE TITLE
Create households GeoJSON based on public information

### ISSUE THREAD

**Issue by lsetiawan** [uw-ssec/post-disaster-comms#34]
## Overview

We'll need household information for users. There are public datasets from 2020 that we can utilize. A combination of the datasets below is needed to filter down data to ONLY Laurelhurst neighborhood:

King County Parcel dataset: https://gis-kingcounty.opendata.arcgis.com/datasets/c7a17b7ad3ec44b7ae64796dca691d72_1722
Seattle Neighborhoods dataset: https://data-seattlecitygis.opendata.arcgis.com/datasets/b4a142f592e94d39a3bf787f3c112c1d

We need this data as GeoJSON.

**Comment by nikiburggraf** [comment]
No longer needed -- shapefile has been provided
