### ISSUE TITLE
Complete software spec

### ISSUE THREAD

**Issue by atambay37** [uw-ssec/post-disaster-comms#6]
Action Items
- [x] Port over information from EOI to software spec
- [x] Ask for User Stories from PI
- [x] Port over User Stories to software spec
- [x] Create a software design specification [RSE]

**Comment by lsetiawan** [comment]
As of 6/10/2024 we received MVP Discussion Notes, User functions list, and User stories. 

Key note from slack:
> note that our discussion is not yet finished and we need to identify from this list of functions on what shall be included in MVP for each account category. We are scheduled to have another discussion next week and pls stay tuned.

Links to slack conversation:
- https://escience-institute.slack.com/archives/C0717F2RK2P/p1718060187582179?thread_ts=1717699328.370999&cid=C0717F2RK2P
- https://escience-institute.slack.com/archives/C0717F2RK2P/p1718074803239759?thread_ts=1717699328.370999&cid=C0717F2RK2P

**Comment by lsetiawan** [comment]
Done
